[package]
name = "tansu"
description = "Apache Kafka compatible broker with S3, PostgreSQL, Apache Iceberg and Delta Lake"
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true
include.workspace = true

[dependencies]
dotenv.workspace = true
tansu-broker.workspace = true
tansu-cli.workspace = true
tansu-sans-io.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
