---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 60s
    scheme: http
    static_configs:
      - targets:
          - minio:9000
