---
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: minio-job
    metrics_path: /minio/metrics/v3
    scrape_interval: 10s
    scheme: http
    static_configs:
      - targets:
          - minio:9000
