[package]
name = "tansu-proxy"
edition.workspace = true
version.workspace = true
license.workspace = true
publish = false

# [lints]
# workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
clap.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
rama.workspace = true
tansu-kafka-sans-io = { path = "../tansu-kafka-sans-io" }
tansu-otel = { path = "../tansu-otel" }
tansu-service = { path = "../tansu-service" }
thiserror.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
